/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
/** adoptedin means adopted into the family
adoptedout means child belonged to the family and was adopted out */
@org.apache.avro.specific.AvroGenerated
public enum AdoptedStatus { 
  not_adopted, adoptedin, adoptedout  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AdoptedStatus\",\"namespace\":\"Gel_BioInf_Models\",\"doc\":\"adoptedin means adopted into the family\\nadoptedout means child belonged to the family and was adopted out\",\"symbols\":[\"not_adopted\",\"adoptedin\",\"adoptedout\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
