/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
/** Affection Status */
@org.apache.avro.specific.AvroGenerated
public enum AffectionStatus { 
  unaffected, affected, unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AffectionStatus\",\"namespace\":\"Gel_BioInf_Models\",\"doc\":\"Affection Status\",\"symbols\":[\"unaffected\",\"affected\",\"unknown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
