/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ComplexGeneticPhenomena { 
  mosaicism, monosomy, disomy, uniparental_disomy, trisomy, other_aneuploidy  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ComplexGeneticPhenomena\",\"namespace\":\"Gel_BioInf_Models\",\"symbols\":[\"mosaicism\",\"monosomy\",\"disomy\",\"uniparental_disomy\",\"trisomy\",\"other_aneuploidy\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
