/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
/** 1K Population */
@org.apache.avro.specific.AvroGenerated
public enum KGSuperPopCategory { 
  AFR, AMR, EAS, EUR, SAS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"KGSuperPopCategory\",\"namespace\":\"Gel_BioInf_Models\",\"doc\":\"1K Population\",\"symbols\":[\"AFR\",\"AMR\",\"EAS\",\"EUR\",\"SAS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
