/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
/** Life Status */
@org.apache.avro.specific.AvroGenerated
public enum LifeStatus { 
  alive, aborted, deceased, unborn, stillborn, miscarriage  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LifeStatus\",\"namespace\":\"Gel_BioInf_Models\",\"doc\":\"Life Status\",\"symbols\":[\"alive\",\"aborted\",\"deceased\",\"unborn\",\"stillborn\",\"miscarriage\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
