/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
/** Sex */
@org.apache.avro.specific.AvroGenerated
public enum Sex { 
  male, female, undetermined  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Sex\",\"namespace\":\"Gel_BioInf_Models\",\"doc\":\"Sex\",\"symbols\":[\"male\",\"female\",\"undetermined\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
