/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package Gel_BioInf_Models;  
@SuppressWarnings("all")
/** This the define a yes/no/unknown case */
@org.apache.avro.specific.AvroGenerated
public enum TernaryOption { 
  yes, no, unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TernaryOption\",\"namespace\":\"Gel_BioInf_Models\",\"doc\":\"This the define a yes/no/unknown case\",\"symbols\":[\"yes\",\"no\",\"unknown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
